In [2]:
import pandas as pd
import numpy as np

In [23]:
df_london = pd.read_csv(
    "/Users/jonahwitte/Desktop/IS_477_Group_Project/Data Folder/London Bloomsbury_AllPollutants_Daily_2024.csv",
    skiprows=7,
)
df_london = df_london.replace("no data", pd.NA)
remove_status = [
    "Date",
    "Nitrogen dioxide",
    "Ozone",
    "PM10 particulate matter (Hourly measured)",
    "PM2.5 particulate matter (Hourly measured)",
    "Sulphur dioxide"
]
df_london = df_london[remove_status]
df_london.head()

#df_deaths = pd.read_csv("/Users/jonahwitte/Desktop/IS_477_Group_Project/Data Folder/Ambient_Air_Pollution_deaths.csv")
#df_deaths.head()

,Date,Nitrogen dioxide,Ozone,PM10 particulate matter (Hourly measured),PM2.5 particulate matter (Hourly measured),Sulphur dioxide
0,2024-01-01,14.130027916666666666666666667,58.799698333333333333333333333,<NA>,<NA>,1.06409625
1,2024-01-02,15.31118625,67.37427875,<NA>,<NA>,1.0529441666666666666666666667
2,2024-01-03,20.68530625,57.878765416666666666666666667,10.95625,5.9267916666666666666666666667,0.9269516666666666666666666667
3,2024-01-04,26.294858333333333333333333333,46.145020416666666666666666667,10.770833333333333333333333333,5.620125,0.9285858333333333333333333333
4,2024-01-05,29.6013275,32.04623,9.079166666666666666666666667,6.5802083333333333333333333333,0.9320441666666666666666666667

In [26]:
pollutant_cols = [
    "Nitrogen dioxide",
    "Ozone",
    "PM10 particulate matter (Hourly measured)",
    "PM2.5 particulate matter (Hourly measured)",
    "Sulphur dioxide"
]
df_london[pollutant_cols] = df_london[pollutant_cols].apply(pd.to_numeric)

In [29]:
df_london["Date"] = pd.to_datetime(df_london["Date"])
df_london["month"] = df_london["Date"].dt.month
#df_london.head()
df_london.groupby("month")[pollutant_cols].mean()

,Nitrogen dioxide,Ozone,PM10 particulate matter (Hourly measured),PM2.5 particulate matter (Hourly measured),Sulphur dioxide
month,,,,,
1,28.829685,43.135347,13.772773,8.115407,0.911953
2,23.982919,52.172779,10.248229,5.789579,1.023630
3,26.246991,49.420550,13.872192,9.387569,0.884156
4,19.000823,65.029955,9.164201,4.921719,0.819167
5,22.559832,59.339686,13.930444,8.963027,0.734561
6,16.628873,63.548864,10.656046,5.660194,0.932766
7,17.600678,55.389528,9.539886,4.825461,0.929680
8,14.589744,61.334271,12.715943,6.786968,0.895497
9,22.156947,48.290328,14.121181,8.357406,0.392267
10,25.820108,37.470175,13.849429,7.456679,0.418058
11,34.974987,21.520993,24.826989,18.815288,0.755781
12,24.610833,37.233166,9.879957,6.109197,NaN